services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mes
      POSTGRES_PASSWORD: mes
      POSTGRES_DB: mesdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  node-api:
    build: ./node-api
    environment:
      DATABASE_URL: postgresql://mes:mes@db:5432/mesdb?schema=public
      JWT_SECRET: super-secret
      PORT: 4000
    depends_on: [db]
    ports: ["4000:4000"]

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://node-api:4000
    depends_on: [node-api]
    ports: ["3000:3000"]

volumes:
  pgdata:
